### ISSUE TITLE
Clean does not delete `.bbl` file

### ISSUE THREAD

**Issue by venkatasg** [mava/Nova-LaTeX#10]
Currently clean calls `latexmk -C` which doesn't delete `bbl` files because of [decisions by the `latexmk` author](https://tex.stackexchange.com/a/83384). Would it make sense to set Clean to `latexmk -C -bibtex` which will delete `bbl` files as well ? Not sure I understand the author's justification that people might not have access to the original `bib` file &mdash; in the context of using TeX in Nova maybe this isn't something to worry about?

**Comment by mava** [comment]
I do agree with you that the default `latexmk -c` behavior is not optimal. In fact, [my own `latexmkrc` file](https://gist.github.com/mava/dac6ea95dca79aa44c9a8023936ea79d#file-latexmkrc-L23) sets `$bibtex_use = 1.5` (“only use *bibtex* if the bib files exist; conditionally delete .bbl files in a cleanup (i.e., delete them only when the bib files all exist)”&#8239;—&#8239;cf. page 31 in [`latexmk`’s manual](https://www.cantab.net/users/johncollins/latexmk/latexmk-481.pdf)).

However, one of the [design ideas](https://github.com/mava/Nova-LaTeX/blob/main/LaTeX.novaextension/README.md#technical-implementation-details) for the extension was this:

> Instead of providing an interface to some of `latexmk`’s many, many configuration options in the extension Preferences, I recommend using `latexmkrc` files. These can be tracked in revision control systems, shared with collaborators, and used in other apps and operating systems.

What do you think? Thanks for your feedback!

**Comment by venkatasg** [comment]
Yeah I agree that this is probably for the best in the sense of obeying the defaults, and any user specified `latexmkrc` files.
Maybe add this as an item in the README of the extension for people who want more from 'Clean' or 'Build'.
