### ISSUE TITLE
Multi-file forward search 

### ISSUE THREAD

**Issue by maxlieblich** [mava/Nova-LaTeX#2]
I have a project with several files (included in the main file using \include). When I do the Run command to sync to the pdf from within one of the included files, two things happen:

1. the process works correctly (i.e., the cursor jumps to the appropriate spot)
2. Skim also up an error saying "[name of included file].pdf could not be opened. The file doesn't exist."

Example: I have a book project. The main file is "book-main-file.tex", and (say) Chapter 3 is included with "\include{chapter3}". If I go to a spot in chapter3.tex and execute Run, Skim jumps to the right spot in the pdf (good!) and *also* pops up an error "The document 'chapter3.pdf' could not be opened. The file doesn't exist." (bad!).

Otherwise, this extension is a great start! Nice work.

**Comment by mava** [comment]
Yes, I know exactly what you mean, and I should’ve mentioned this issue in the extension’s README. Sorry! Unfortunately, I can’t think of an easy way to fix it — but I’ll keep thinking about it.

Thanks so much for your report and kind words! (And nice to “meet” you, Max! I’m also a [mathematician](https://www.albany.edu/~mv312143/) and I know of you and your work, even though I think that we never crossed paths.)
