### ISSUE TITLE
Extension isn't active for files with suffix .latex

### ISSUE THREAD

**Issue by dahanbn** [mava/Nova-LaTeX#3]
I have same LaTeX template files that I use to convert my markdown files to pdf via Latex.  Those have the suffix .latex. Files ending with .latex will not automatically recognised as LaTeX files. Maybe that could be changed.

**Comment by mava** [comment]
You may have already tried this, but in [Preferences → Editor → Files](https://library.panic.com/nova/preferences/#files-1) one can tell Nova to use the LaTeX syntax for any `.latex` file. The extension should activate whenever a file with LaTeX syntax is opened. Does it work? (It works for me.) Let me know. Thanks!
<img width="792" alt="Preferences → Editor → Files" src="https://user-images.githubusercontent.com/164458/159144617-9bcab26c-d7f9-4e08-aec5-60095bceab1f.png">

**Comment by dahanbn** [comment]
Thanks, for the quick follow up. I have tried to find that option but am I new to Nova and haven't found it. :-)

Now, I have configured it. Maybe you could add those association as default in your extension.

**Comment by mava** [comment]
Great! I don’t think that `.latex` is a common extension, so I’m not sure about adding it&#8239;—&#8239;but I’ll consider your request. Thank you!
