### ISSUE TITLE
Clean Build feature request

### ISSUE THREAD

**Issue by venkatasg** [mava/Nova-LaTeX#9]
Hello! Would it be possible to add a build command 'Clean Build', which cleans all temporary files away, and then executes a build?

I love this extension, thank you!

**Comment by mava** [comment]
Thank you for the feature request and for your kind words, Venkat!

I had thought about it, too, but the way the extension is implemented (through Nova’s tasks) makes it complicated. So, whenever I need a “Clean Build” myself, I just hit ⇧⌘K followed by ⌘B (to invoke the Clean and Build tasks one after the other).

(More details: there seems to be no way in Nova’s API to invoke tasks from a command. Of course, one could refactor the tasks’ code in a separate command, but then the compilation results would not automatically appear in the Reports sidebar, the UI (task progress, notifications, interruption, …) would be different and inconsistent with the separate Build and Clean tasks, etc…. Or, one could add an option in the extension’s Preferences tab to always perform a “Clean Build,” corresponding to the `-gg` option in `latexmk`, but that’s probably not what anyone wants. So, I can’t think of a good way to implement this, one that would be better than just doing ⇧⌘K + ⌘B when needed.)

**Comment by venkatasg** [comment]
Interesting. I glanced through the source code and assumed you could just chain these two commands together. In this case, the reports sidebar would just show the report from the build, not the clean. To be concrete, I mean chaining clean and build commands in [line 158](https://github.com/mava/Nova-LaTeX/blob/e1d359777d15ca669b5fe8c0d24d9f7a89e17945/LaTeX.novaextension/Scripts/main.js#L158) of `main.js`. But this isn't possible?

**Comment by mava** [comment]
Yes, but (if I understand you correctly) then every Build would be a “Clean then Build,” which is not what most people would want as default Build behavior (especially if working with large complex documents). Or am I misunderstanding you?

**Comment by venkatasg** [comment]
Oh no, I meant adding *another* command within the Build menu. Right now, when I long click it, it shows Build and Clean. Is it not possible to add another item 'Clean Build' that does the chained command? A separate command is what I'm asking for.

**Comment by mava** [comment]
OK, now I understand the source of the confusion. The problem is that Nova’s Tasks can only “define behavior for *up to three* different actions: Build, Run, Clean[.”](https://help.panic.com/nova/run-tasks/) It’s not possible to add another command to that menu, unfortunately.

**Comment by venkatasg** [comment]
Ah ok, got it. I didn't know of that limitation. Thanks for answering my questions!
